# Generated by Django 4.2.1 on 2023-05-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCaptcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=200)),
                ('text_solution', models.TextField()),
                ('stars_rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comments', models.TextField()),
            ],
        ),
    ]
